# Generated by Django 4.1.1 on 2022-12-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaguestat', '0002_fixtures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguetable',
            name='gd',
            field=models.IntegerField(default=0),
        ),
    ]
