# Generated by Django 4.1.1 on 2022-12-08 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('leaguestat', '0003_alter_leaguetable_gd'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fixtures',
            unique_together={('teamA', 'teamB')},
        ),
    ]
