# Generated by Django 4.1.1 on 2022-12-11 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('leaguestat', '0009_alter_fixtures_matchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguetable',
            name='teamName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team', unique=True),
        ),
    ]
