# Generated by Django 4.1.1 on 2022-12-03 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_player_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='num',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
