# Generated by Django 4.1.1 on 2022-12-03 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_alter_player_height_alter_player_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pID',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
