# Generated by Django 4.1.1 on 2022-12-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_alter_player_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='Unsigned', max_length=20),
        ),
    ]
