# Generated by Django 4.1.1 on 2022-12-10 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pID',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
