from django.core.management.base import BaseCommand
from leaguestat.models import Fixtures, LeagueTable
from player.models import *
from team.models import Team, TeamPlayers
class Command(BaseCommand):
    def handle(self, *args, **options):

        #seeding player data

        Player.objects.all().delete()

        p1 = Player(pID = 1000, fName = "Phil" , lName = "Smith", height = 156, weight = 60.5, num = 10, position = "Forward")
        p1.save()
        p2 = Player(pID = 1001, fName = "Jude" , lName = "Evans", height = 168, weight = 67.5, num = 9, position = "Forward")
        p2.save()
        p3 = Player(pID = 1002, fName = "Harry" , lName = "Walker", height = 176, weight = 68, num = 11, position = "Forward")
        p3.save()
        p4 = Player(pID = 1003, fName = "Jordan" , lName = "Wilson", height = 156, weight = 67.5, num = 7, position = "Defender")
        p4.save()
        p5 = Player(pID = 1004, fName = "Robert" , lName = "Smith", height = 177, weight = 60.5, num = 8, position = "Defender")
        p5.save()
        p6 = Player(pID = 1005, fName = "David" , lName = "White", height = 144, weight = 67.5, num = 6, position = "Defender")
        p6.save()
        p7 = Player(pID = 1006, fName = "Richard" , lName = "Clarke", height = 150, weight = 68, num = 13, position = "Midfielder")
        p7.save()
        p8 = Player(pID = 1007, fName = "Thomas" , lName = "Hall", height = 169, weight = 67.5, num = 15, position = "Midfielder")
        p8.save()
        p9 = Player(pID = 1008, fName = "Daniel" , lName = "Lewis", height = 152, weight = 60.5, num = 19, position = "Midfielder")
        p9.save()
        p10 = Player(pID = 1009, fName = "Matthew" , lName = "Harris", height = 158, weight = 67.5, num = 18, position = "Midfielder")
        p10.save()
        p11 = Player(pID = 1010, fName = "Mark" , lName = "Wood", height = 168, weight = 68, num = 1, position = "Goal Keeper")
        p11.save()

        p12 = Player(pID = 1011, fName = "Charles" , lName = "Baker", height = 156, weight = 60.5, num = 10, position = "Forward")
        p12.save()
        p13 = Player(pID = 1012, fName = "Donald" , lName = "Lee", height = 168, weight = 67.5, num = 9, position = "Forward")
        p13.save()
        p14= Player(pID = 1013, fName = "Paul" , lName = "Allen", height = 176, weight = 68, num = 11, position = "Forward")
        p14.save()
        p15 = Player(pID = 1014, fName = "Joshua" , lName = "James", height = 177, weight = 60.5, num = 20, position = "Defender")
        p15.save()
        p16 = Player(pID = 1015, fName = "Andrew" , lName = "Scott", height = 144, weight = 67.5, num = 21, position = "Defender")
        p16.save()
        p17 = Player(pID = 1016, fName = "Steven" , lName = "Clarke", height = 147, weight = 68, num = 13, position = "Midfielder")
        p17.save()
        p18 = Player(pID = 1017, fName = "Mark" , lName = "Watson", height = 179, weight = 67.5, num = 15, position = "Midfielder")
        p18.save()
        p19 = Player(pID = 1018, fName = "Kevin" , lName = "Lewis", height = 152, weight = 70.5, num = 19, position = "Midfielder")
        p19.save()
        p20 = Player(pID = 1019, fName = "Brian" , lName = "Parker", height = 158, weight = 80.5, num = 18, position = "Midfielder")
        p20.save()
        p21 = Player(pID = 1020, fName = "George" , lName = "Wood", height = 168, weight = 68, num = 1, position = "Goal Keeper")
        p21.save()
        p22 = Player(pID = 1021, fName = "Anthony" , lName = "Price", height = 156, weight = 70.5, num = 7, position = "Defender")
        p22.save()
       
        p23 = Player(pID = 1022, fName = "Phil" , lName = "Smith", height = 156, weight = 60.5, num = 10, position = "Forward")
        p23.save()
        p24 = Player(pID = 1023, fName = "Jude" , lName = "Evans", height = 168, weight = 67.5, num = 9, position = "Forward")
        p24.save()
        p25 = Player(pID = 1024, fName = "Harry" , lName = "Walker", height = 176, weight = 68, num = 11, position = "Forward")
        p25.save()
        p26= Player(pID = 1025, fName = "Jordan" , lName = "Wilson", height = 156, weight = 67.5, num = 7, position = "Defender")
        p26.save()
        p27= Player(pID = 1026, fName = "Robert" , lName = "Smith", height = 177, weight = 68.5, num = 8, position = "Defender")
        p27.save()
        p28= Player(pID = 1027, fName = "David" , lName = "White", height = 144, weight = 67.5, num = 6, position = "Defender")
        p28.save()
        p29 = Player(pID = 1028, fName = "Richard" , lName = "Clarke", height = 150, weight = 68, num = 13, position = "Midfielder")
        p29.save()
        p30 = Player(pID = 1029, fName = "Thomas" , lName = "Hall", height = 169, weight = 67.5, num = 15, position = "Midfielder")
        p30.save()
        p31 = Player(pID = 1030, fName = "Daniel" , lName = "Lewis", height = 152, weight = 75.5, num = 19, position = "Midfielder")
        p31.save()
        p32 = Player(pID = 1031, fName = "Matthew" , lName = "Harris", height = 158, weight = 67.5, num = 18, position = "Midfielder")
        p32.save()
        p33 = Player(pID = 1032, fName = "Mark" , lName = "Wood", height = 168, weight = 68, num = 1, position = "Goal Keeper")
        p33.save()

        p34 = Player(pID = 1033, fName = "Donald" , lName = "Wright", height = 188, weight = 67.5, num = 9, position = "Forward")
        p34.save()
        p35= Player(pID = 1034, fName = "Mitchell" , lName = "Robinson", height = 186, weight = 68, num = 11, position = "Forward")
        p35.save()
        p36 = Player(pID = 1035, fName = "Neon" , lName = "Bell", height = 179, weight = 67.5, num = 20, position = "Defender")
        p36.save()
        p37 = Player(pID = 1036, fName = "Matt" , lName = "Cox", height = 166, weight = 68.5, num = 21, position = "Defender")
        p37.save()
        p38 = Player(pID = 1037, fName = "Keil" , lName = "Clarke", height = 151, weight = 72, num = 13, position = "Midfielder")
        p38.save()
        p39 = Player(pID = 1038, fName = "Mark" , lName = "Murphy", height = 163, weight = 73.5, num = 15, position = "Midfielder")
        p39.save()
        p40 = Player(pID = 1039, fName = "Fren" , lName = "Marshall", height = 162, weight = 70.5, num = 19, position = "Midfielder")
        p40.save()
        p41 = Player(pID = 1040, fName = "Brian" , lName = "Anderson", height = 174, weight = 80.5, num = 18, position = "Midfielder")
        p41.save()
        p42 = Player(pID = 1041, fName = "Keith" , lName = "Jones", height = 168, weight = 81, num = 1, position = "Goal Keeper")
        p42.save()
        p43 = Player(pID = 1042, fName = "Zachary" , lName = "Webb", height = 156, weight = 82.5, num = 7, position = "Defender")
        p43.save()
        p44 = Player(pID = 1043, fName = "Kyle" , lName = "Roberts", height = 166, weight = 60.5, num = 10, position = "Forward")
        p44.save()

        p45 = Player(pID = 1044, fName = "Louis" , lName = "Palmer", height = 177, weight = 60.5, num = 10, position = "Forward")
        p45.save()
        p46 = Player(pID = 1045, fName = "Bobby" , lName = "Evans", height = 168, weight = 70, num = 9, position = "Forward")
        p46.save()
        p47 = Player(pID = 1046, fName = "Vincent" , lName = "Graham", height = 177, weight = 68.5, num = 11, position = "Forward")
        p47.save()
        p48 = Player(pID = 1047, fName = "Ralph" , lName = "Wilson", height = 156, weight = 68.5, num = 7, position = "Defender")
        p48.save()
        p49 = Player(pID = 1048, fName = "Roy" , lName = "Hervey", height = 172, weight = 63.5, num = 8, position = "Defender")
        p49.save()
        p50 = Player(pID = 1049, fName = "David" , lName = "Lloyd", height = 184, weight = 64.5, num = 6, position = "Defender")
        p50.save()
        p51 = Player(pID = 1050, fName = "Mason" , lName = "Clarke", height = 161, weight = 61, num = 13, position = "Midfielder")
        p51.save()
        p52 = Player(pID = 1051, fName = "Tom" , lName = "Fisher", height = 169, weight = 69.5, num = 8, position = "Midfielder")
        p52.save()
        p53 = Player(pID = 1052, fName = "Danis" , lName = "Dixon", height = 162, weight = 64.5, num = 12, position = "Midfielder")
        p53.save()
        p54 = Player(pID = 1053, fName = "Alan" , lName = "Harris", height = 148, weight = 67.5, num = 18, position = "Midfielder")
        p54.save()
        p55 = Player(pID = 1054, fName = "Mark" , lName = "jenkins", height = 178, weight = 68, num = 1, position = "Goal Keeper")
        p55.save()

        p56 = Player(pID = 1055, fName = "Stephen" , lName = "Hill", height = 177, weight =71.5, num = 10, position = "Forward")
        p56.save()
        p57 = Player(pID = 1056, fName = "Justin" , lName = "Cooper", height = 168, weight = 70, num = 9, position = "Forward")
        p57.save()
        p58 = Player(pID = 1057, fName = "Larry" , lName = "Martin", height = 177, weight = 68.5, num = 11, position = "Forward")
        p58.save()
        p59 = Player(pID = 1058, fName = "Ryan" , lName = "Hughes", height = 156, weight = 68.5, num = 7, position = "Defender")
        p59.save()
        p60 = Player(pID = 1059, fName = "Edward" , lName = "Turner", height = 172, weight = 63.5, num = 8, position = "Defender")
        p60.save()
        p61 = Player(pID = 1060, fName = "Eric" , lName = "Green", height = 184, weight = 74.5, num = 6, position = "Defender")
        p61.save()
        p62 = Player(pID = 1061, fName = "Nicholas" , lName = "Murphy", height = 161, weight = 67, num = 13, position = "Midfielder")
        p62.save()
        p63 = Player(pID = 1062, fName = "Gary" , lName = "Simpson", height = 169, weight = 67.5, num = 8, position = "Midfielder")
        p63.save()
        p64 = Player(pID = 1063, fName = "Ronald" , lName = "Anderson", height = 162, weight = 67.5, num = 12, position = "Midfielder")
        p64.save()
        p65 = Player(pID = 1064, fName = "Frank" , lName = "Ellis", height = 148, weight = 68.5, num = 18, position = "Midfielder")
        p65.save()
        p66 = Player(pID = 1065, fName = "Alex" , lName = "jenkins", height = 178, weight = 68, num = 1, position = "Goal Keeper")
        p66.save()

        self.stdout.write('done Player') 

        #Seeding team data
        Team.objects.all().delete()
        t1 = Team(teamID = 1, teamName = "United Comp Science", managerName = "Peter Ward", teamSponsor="Adidas" )
        t1.save()
        t2 = Team(teamID = 2, teamName = "FC Electronic Eng. ", managerName = "Jeremy Turner", teamSponsor="Nike" )
        t2.save()
        t3 = Team(teamID = 3, teamName = "Team Mechanical", managerName = "Matt Clark", teamSponsor="Puma" )
        t3.save()
        t4 = Team(teamID = 4, teamName = "FC Civil", managerName = "Robin Baker", teamSponsor="Fly Emirates" )
        t4.save()
        t5 = Team(teamID = 5, teamName = "United Chemistry", managerName = "Austin Lee", teamSponsor="Ethihad Airways" )
        t5.save()
        t6 = Team(teamID = 6, teamName = "FC Mathematics", managerName = "Arthur Parker", teamSponsor="Qatar Airways" )
        t6.save()

        TeamPlayers.objects.all().delete()
        
        tp1 = TeamPlayers(teamID = t1, player = p1)
        tp1.save()
        tp2 = TeamPlayers(teamID = t1, player = p2)
        tp2.save()
        tp3 = TeamPlayers(teamID = t1, player = p3)
        tp3.save()
        tp4 = TeamPlayers(teamID = t1, player = p4)
        tp4.save()
        tp5 = TeamPlayers(teamID = t1, player = p5)
        tp5.save()
        tp6 = TeamPlayers(teamID = t1, player = p6)
        tp6.save()
        tp7 = TeamPlayers(teamID = t1, player = p7)
        tp7.save()
        tp8 = TeamPlayers(teamID = t1, player = p8)
        tp8.save()
        tp9 = TeamPlayers(teamID = t1, player = p9)
        tp9.save()
        tp10 = TeamPlayers(teamID = t1, player = p10)
        tp10.save()
        tp11 = TeamPlayers(teamID = t1, player = p11)
        tp11.save()

        tp1 = TeamPlayers(teamID = t2, player = p12)
        tp1.save()
        tp2 = TeamPlayers(teamID = t2, player = p13)
        tp2.save()
        tp3 = TeamPlayers(teamID = t2, player = p14)
        tp3.save()
        tp4 = TeamPlayers(teamID = t2, player = p15)
        tp4.save()
        tp5 = TeamPlayers(teamID = t2, player = p16)
        tp5.save()
        tp6 = TeamPlayers(teamID = t2, player = p17)
        tp6.save()
        tp7 = TeamPlayers(teamID = t2, player = p18)
        tp7.save()
        tp8 = TeamPlayers(teamID = t2, player = p19)
        tp8.save()
        tp9 = TeamPlayers(teamID = t2, player = p20)
        tp9.save()
        tp10 = TeamPlayers(teamID = t2, player = p21)
        tp10.save()
        tp11 = TeamPlayers(teamID = t2, player = p22)
        tp11.save()
       
        tp1 = TeamPlayers(teamID = t3, player = p23)
        tp1.save()
        tp2 = TeamPlayers(teamID = t3, player = p24)
        tp2.save()
        tp3 = TeamPlayers(teamID = t3, player = p25)
        tp3.save()
        tp4 = TeamPlayers(teamID = t3, player = p26)
        tp4.save()
        tp5 = TeamPlayers(teamID = t3, player = p27)
        tp5.save()
        tp6 = TeamPlayers(teamID = t3, player = p28)
        tp6.save()
        tp7 = TeamPlayers(teamID = t3, player = p29)
        tp7.save()
        tp8 = TeamPlayers(teamID = t3, player = p30)
        tp8.save()
        tp9 = TeamPlayers(teamID = t3, player = p31)
        tp9.save()
        tp10 = TeamPlayers(teamID = t3, player = p32)
        tp10.save()
        tp11 = TeamPlayers(teamID = t3, player = p33)
        tp11.save()

        tp1 = TeamPlayers(teamID = t4, player = p34)
        tp1.save()
        tp2 = TeamPlayers(teamID = t4, player = p35)
        tp2.save()
        tp3 = TeamPlayers(teamID = t4, player = p36)
        tp3.save()
        tp4 = TeamPlayers(teamID = t4, player = p37)
        tp4.save()
        tp5 = TeamPlayers(teamID = t4, player = p38)
        tp5.save()
        tp6 = TeamPlayers(teamID = t4, player = p39)
        tp6.save()
        tp7 = TeamPlayers(teamID = t4, player = p40)
        tp7.save()
        tp8 = TeamPlayers(teamID = t4, player = p41)
        tp8.save()
        tp9 = TeamPlayers(teamID = t4, player = p42)
        tp9.save()
        tp10 = TeamPlayers(teamID = t4, player = p43)
        tp10.save()
        tp11 = TeamPlayers(teamID = t4, player = p44)
        tp11.save()

        tp1 = TeamPlayers(teamID = t5, player = p45)
        tp1.save()
        tp2 = TeamPlayers(teamID = t5, player = p46)
        tp2.save()
        tp3 = TeamPlayers(teamID = t5, player = p47)
        tp3.save()
        tp4 = TeamPlayers(teamID = t5, player = p48)
        tp4.save()
        tp5 = TeamPlayers(teamID = t5, player = p49)
        tp5.save()
        tp6 = TeamPlayers(teamID = t5, player = p50)
        tp6.save()
        tp7 = TeamPlayers(teamID = t5, player = p51)
        tp7.save()
        tp8 = TeamPlayers(teamID = t5, player = p52)
        tp8.save()
        tp9 = TeamPlayers(teamID = t5, player = p53)
        tp9.save()
        tp10 = TeamPlayers(teamID = t5, player = p54)
        tp10.save()
        tp11 = TeamPlayers(teamID = t5, player = p55)
        tp11.save()

        tp1 = TeamPlayers(teamID = t6, player = p56)
        tp1.save()
        tp2 = TeamPlayers(teamID = t6, player = p57)
        tp2.save()
        tp3 = TeamPlayers(teamID = t6, player = p58)
        tp3.save()
        tp4 = TeamPlayers(teamID = t6, player = p59)
        tp4.save()
        tp5 = TeamPlayers(teamID = t6, player = p60)
        tp5.save()
        tp6 = TeamPlayers(teamID = t6, player = p61)
        tp6.save()
        tp7 = TeamPlayers(teamID = t6, player = p62)
        tp7.save()
        tp8 = TeamPlayers(teamID = t6, player = p63)
        tp8.save()
        tp9 = TeamPlayers(teamID = t6, player = p64)
        tp9.save()
        tp10 = TeamPlayers(teamID = t6, player = p65)
        tp10.save()
        tp11 = TeamPlayers(teamID = t6, player = p66)
        tp11.save()
        
        self.stdout.write('done Teams and TeamPlayers') 

        LeagueTable.objects.all().delete()
        lt1 = LeagueTable(teamName = t1)
        lt1.save()
        lt2 = LeagueTable(teamName = t2)
        lt2.save()
        lt3 = LeagueTable(teamName = t3)
        lt3.save()
        lt4 = LeagueTable(teamName = t4)
        lt4.save()
        lt5 = LeagueTable(teamName = t5)
        lt5.save()
        lt6 = LeagueTable(teamName = t6)
        lt6.save()

        self.stdout.write('done LeagueTable') 
